CREATE SCHEMA CRM;

CREATE TABLE CRM.TIPO_MEDIO
(

    CODIGO      SERIAL       NOT NULL,
    NOMBRE      VARCHAR(200) NOT NULL,
    DESCRIPCION VARCHAR(200) NOT NULL,
    VALOR_PROM  INT          NOT NULL,
    ESTADO      BOOLEAN      NOT NULL,

    CONSTRAINT TIPO_MEDIO_PK
        PRIMARY KEY (CODIGO)

);

CREATE UNIQUE INDEX TIPO_MEDIO_UINDEX
    ON CRM.TIPO_MEDIO (CODIGO);

COMMENT ON TABLE CRM.TIPO_MEDIO IS 'TABLA QUE DESCRIBE LOS TIPOS DE MEDIO DISPONIBLES PARA SER CONSUMIDOS.';
COMMENT ON COLUMN CRM.TIPO_MEDIO.CODIGO IS 'CÓDIGO DEL TIPO DE MEDIO DE DIVULGACIÓN (ESCRITO, RADIO, TV, INTERNET)';
COMMENT ON COLUMN CRM.TIPO_MEDIO.NOMBRE IS 'NOMBRE DEL MEDIO';
COMMENT ON COLUMN CRM.TIPO_MEDIO.DESCRIPCION IS 'DESCRIPCIÓN DEL MEDIO';
COMMENT ON COLUMN CRM.TIPO_MEDIO.VALOR_PROM IS 'VALOR PROMEDIO DEL MEDIO';
COMMENT ON COLUMN CRM.TIPO_MEDIO.ESTADO IS 'ACTIVO (1), INACTIVO (0)';

CREATE TABLE CRM.PERIODO
(

    CODIGO       SERIAL  NOT NULL,
    FECHA_INICIO DATE    NOT NULL,
    FECHA_FIN    DATE    NOT NULL,
    ESTADO       BOOLEAN NOT NULL,

    CONSTRAINT PERIODO_PK
        PRIMARY KEY (CODIGO)

);

CREATE UNIQUE INDEX PERIODO_UINDEX
    ON CRM.PERIODO (CODIGO);

COMMENT ON TABLE CRM.PERIODO IS 'TABLA QUE DESCRIBE EL PERIODO DE PUBLICIDAD DE LA CAMPAÑA.';
COMMENT ON COLUMN CRM.PERIODO.CODIGO IS 'CÓDIGO DEL PERIODO DE PUBLICIDAD.';
COMMENT ON COLUMN CRM.PERIODO.FECHA_INICIO IS 'FECHA INICIO.';
COMMENT ON COLUMN CRM.PERIODO.FECHA_FIN IS 'FECHA FINAL.';
COMMENT ON COLUMN CRM.PERIODO.ESTADO IS 'ACTIVO (1), INACTIVO (0)';

CREATE TABLE CRM.CAMPANIA
(

    CODIGO       SERIAL       NOT NULL,
    NOMBRE       VARCHAR(200) NOT NULL,
    DESCRIPCION  VARCHAR(200) NOT NULL,
    FECHA_INICIO DATE         NOT NULL,
    FECHA_FIN    DATE         NOT NULL,
    PERIODO_COD  INT          NOT NULL,
    VALOR        DECIMAL      NOT NULL,
    ESTADO       BOOLEAN      NOT NULL,

    CONSTRAINT CAMPANIA_PK
        PRIMARY KEY (CODIGO),

    CONSTRAINT CAMPANIA_PERIODO_FK
        FOREIGN KEY (PERIODO_COD) REFERENCES CRM.PERIODO (CODIGO)
            ON UPDATE CASCADE ON DELETE CASCADE

);

CREATE UNIQUE INDEX CAMPANIA_UINDEX
    ON CRM.CAMPANIA (CODIGO);

COMMENT ON TABLE CRM.CAMPANIA IS 'TABLA QUE DESCRIBE LAS CAMPAÑAS DE LA COMPAÑÍA.';
COMMENT ON COLUMN CRM.CAMPANIA.CODIGO IS 'CÓDIGO DE LA CAMPAÑA PUBLICITARIA';
COMMENT ON COLUMN CRM.CAMPANIA.NOMBRE IS 'NOMBRE DE LA CAMPAÑA PUBLICITARIA';
COMMENT ON COLUMN CRM.CAMPANIA.DESCRIPCION IS 'DESCRIPCIÓN DE LA CAMPAÑA PUBLICITARIA';
COMMENT ON COLUMN CRM.CAMPANIA.FECHA_INICIO IS 'FECHA DE INICIO DE LA CAMPAÑA PUBLICITARIA';
COMMENT ON COLUMN CRM.CAMPANIA.FECHA_FIN IS 'FECHA DE FINALIZACIÓN DE LA CAMPAÑA PUBLICITARIA';
COMMENT ON COLUMN CRM.CAMPANIA.PERIODO_COD IS 'CÓDIGO DEL PERIODO ASIGNADO A LA CAMPAÑA';
COMMENT ON COLUMN CRM.CAMPANIA.VALOR IS 'PRECIO PROMEDIO DE LA CAMPAÑA PUBLICITARIA';
COMMENT ON COLUMN CRM.CAMPANIA.ESTADO IS 'ACTIVO (1), INACTIVO (0)';

CREATE TABLE CRM.EVENTO
(

    CODIGO       SERIAL       NOT NULL,
    NOMBRE       VARCHAR(200) NOT NULL,
    DESCRIPCION  VARCHAR(200) NOT NULL,
    FECHA        DATE         NOT NULL,
    CAMPANIA_COD INT          NOT NULL,
    ESTADO       BOOLEAN      NOT NULL,

    CONSTRAINT EVENTO_PK
        PRIMARY KEY (CODIGO),

    CONSTRAINT EVENTO_CAMPANIA_FK
        FOREIGN KEY (CAMPANIA_COD) REFERENCES CRM.CAMPANIA (CODIGO)
            ON UPDATE CASCADE ON DELETE CASCADE

);

CREATE UNIQUE INDEX EVENTO_UINDEX
    ON CRM.EVENTO (CODIGO);

COMMENT ON TABLE CRM.EVENTO IS 'TABLA QUE DESCRIBE LOS EVENTOS DE LA COMPAÑÍA.';
COMMENT ON COLUMN CRM.EVENTO.CODIGO IS 'CÓDIGO DEL EVENTO';
COMMENT ON COLUMN CRM.EVENTO.NOMBRE IS 'NOMBRE DEL EVENTO';
COMMENT ON COLUMN CRM.EVENTO.DESCRIPCION IS 'DESCRIPCIÓN DEL EVENTO';
COMMENT ON COLUMN CRM.EVENTO.FECHA IS 'FECHA DEL EVENTO';
COMMENT ON COLUMN CRM.EVENTO.CAMPANIA_COD IS 'CÓDIGO DE LA CAMPAÑA ASIGNADA AL EVENTO';
COMMENT ON COLUMN CRM.EVENTO.ESTADO IS 'ACTIVO (1), INACTIVO (0)';

CREATE TABLE CRM.RECURSO
(

    CODIGO      SERIAL       NOT NULL,
    NOMBRE      VARCHAR(200) NOT NULL,
    TIPO        INT          NOT NULL,
    DESCRIPCION VARCHAR(200),
    VALOR       DECIMAL      NOT NULL,

    CONSTRAINT RECURSO_PK
        PRIMARY KEY (CODIGO)

);

CREATE UNIQUE INDEX RECURSO_UINDEX
    ON CRM.RECURSO (CODIGO);

COMMENT ON TABLE CRM.RECURSO IS 'TABLA QUE DESCRIBE LOS RECURSOS CON LOS QUE CUENTA LA COMPAÑÍA.';
COMMENT ON COLUMN CRM.RECURSO.CODIGO IS 'CÓDIGO DEL RECURSO';
COMMENT ON COLUMN CRM.RECURSO.NOMBRE IS 'NOMBRE DEL RECURSO';
COMMENT ON COLUMN CRM.RECURSO.DESCRIPCION IS 'DESCRIPCIÓN DEL RECURSO';
COMMENT ON COLUMN CRM.RECURSO.TIPO IS 'TIPO DEL RECURSO';
COMMENT ON COLUMN CRM.RECURSO.VALOR IS 'COSTO PROMEDIO DEL RECURSO';

CREATE TABLE CRM.MEDIO
(

    CODIGO         SERIAL       NOT NULL,
    NOMBRE         VARCHAR(200) NOT NULL,
    DESCRIPCION    VARCHAR(200) NOT NULL,
    TIPO_MEDIO_COD INT          NOT NULL,
    EVENTO_COD     INT          NOT NULL,
    RECURSO_COD    INT          NOT NULL,
    VALOR          DECIMAL      NOT NULL,
    ESTADO         BOOLEAN      NOT NULL,

    CONSTRAINT MEDIO_PK
        PRIMARY KEY (CODIGO),

    CONSTRAINT MEDIO_TIPO_MEDIO_FK
        FOREIGN KEY (TIPO_MEDIO_COD) REFERENCES CRM.TIPO_MEDIO (CODIGO)
            ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT MEDIO_EVENTO_FK
        FOREIGN KEY (EVENTO_COD) REFERENCES CRM.EVENTO (CODIGO)
            ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT MEDIO_RECURSO_FK
        FOREIGN KEY (RECURSO_COD) REFERENCES CRM.RECURSO (CODIGO)
            ON UPDATE CASCADE ON DELETE CASCADE

);

COMMENT ON TABLE CRM.MEDIO IS 'TABLA QUE DESCRIBE LOS MEDIOS PUBLICITARIOS DISPONIBLES PARA SER CONSUMIDOS.';
COMMENT ON COLUMN CRM.MEDIO.CODIGO IS 'CÓDIGO DEL RECURSO';
COMMENT ON COLUMN CRM.MEDIO.NOMBRE IS 'NOMBRE DEL RECURSO';
COMMENT ON COLUMN CRM.MEDIO.DESCRIPCION IS 'DESCRIPCIÓN DEL MEDIO';
COMMENT ON COLUMN CRM.MEDIO.TIPO_MEDIO_COD IS 'CÓDIGO CORRESPONDIENTE AL TIPO DEL MEDIO A CONSUMIR';
COMMENT ON COLUMN CRM.MEDIO.EVENTO_COD IS 'CÓDIGO CORRESPONDIENTE AL EVENTO DEL MEDIO A CONSUMIR';
COMMENT ON COLUMN CRM.MEDIO.RECURSO_COD IS 'CÓDIGO CORRESPONDIENTE AL RECUSO DEL MEDIO A CONSUMIR';
COMMENT ON COLUMN CRM.MEDIO.VALOR IS 'COSTO PROMEDIO DEL MEDIO A CONSUMIR';
COMMENT ON COLUMN CRM.MEDIO.ESTADO IS 'ACTIVO (1), INACTIVO (0)';

CREATE UNIQUE INDEX MEDIO_UINDEX
    ON CRM.MEDIO (CODIGO);


CREATE SCHEMA FINANZAS;

CREATE TABLE FINANZAS.PLAN_CONTABLE
(
    CODIGO       INT PRIMARY KEY        NOT NULL,
    NOMBRE       CHARACTER VARYING(100) NOT NULL,
    DESCRIPCION  CHARACTER VARYING(300) NOT NULL,
    TIPO         INT                    NOT NULL,
    VIGENCIA     DATE                   NOT NULL,
    CODIGO_PADRE INT
);

COMMENT ON TABLE FINANZAS.PLAN_CONTABLE
    IS 'TABLA DONDE SE ALMACENAN TODO EL PLAN UNICO DE CUENTAS ';

COMMENT ON COLUMN FINANZAS.PLAN_CONTABLE.CODIGO IS 'CÓDIGO DE LA CUENTA – PUC';
COMMENT ON COLUMN FINANZAS.PLAN_CONTABLE.NOMBRE IS 'NOMBRE DE LA CUENTA';
COMMENT ON COLUMN FINANZAS.PLAN_CONTABLE.DESCRIPCION IS 'DESCRIPCIÓN DE LA CUENTA';
COMMENT ON COLUMN FINANZAS.PLAN_CONTABLE.TIPO IS 'CLASE(1), GRUPO(2),CUENTA(3), SUBCUENTA(4)';
COMMENT ON COLUMN FINANZAS.PLAN_CONTABLE.VIGENCIA IS 'FECHA DE INICIO DE VIGENCIA';
COMMENT ON COLUMN FINANZAS.PLAN_CONTABLE.CODIGO_PADRE IS 'IDENTIFICADOR DE PADRE';

ALTER TABLE FINANZAS.PLAN_CONTABLE
    ADD CONSTRAINT FK_PLANCONTABLE_PLANCONTABLE FOREIGN KEY (CODIGO_PADRE)
        REFERENCES FINANZAS.PLAN_CONTABLE (CODIGO);

CREATE TABLE FINANZAS.PERIODO
(
    CODIGO       SERIAL PRIMARY KEY NOT NULL,
    FECHA_INICIO DATE               NOT NULL,
    FECHA_FIN    DATE               NOT NULL,
    ESTADO       BOOLEAN            NOT NULL

);

COMMENT ON TABLE FINANZAS.PERIODO
    IS 'TABLA DONDE SE ALMACENAN EL PERIODO CONTABLE ';

COMMENT ON COLUMN FINANZAS.PERIODO.CODIGO IS 'CODIGO DEL PERIODO';
COMMENT ON COLUMN FINANZAS.PERIODO.FECHA_INICIO IS 'FECHA INICIO';
COMMENT ON COLUMN FINANZAS.PERIODO.FECHA_FIN IS 'FECHA FINAL';
COMMENT ON COLUMN FINANZAS.PERIODO.ESTADO IS 'ACTIVO (1), INACTIVO (0)';

CREATE TABLE FINANZAS.LIBRO_MAYOR
(
    PLAN_CONTABLE_COD SERIAL  NOT NULL,
    PERIODO_COD       INT     NOT NULL,
    DEBE              DECIMAL NOT NULL,
    HABER             DECIMAL NOT NULL,
    FECHA             DATE    NOT NULL,
    ESTADO            BOOLEAN NOT NULL,
    PRIMARY KEY (PLAN_CONTABLE_COD, PERIODO_COD)
);

COMMENT ON TABLE FINANZAS.LIBRO_MAYOR
    IS 'TABLA DONDE SE ALMACENAN EL LIBRO MAYOR';

COMMENT ON COLUMN FINANZAS.LIBRO_MAYOR.PLAN_CONTABLE_COD IS 'CÓDIGO DE LA TABLA PLAN_CONTABLE';
COMMENT ON COLUMN FINANZAS.LIBRO_MAYOR.PERIODO_COD IS 'CÓDIGO DEL PERIODO CONTABLE';
COMMENT ON COLUMN FINANZAS.LIBRO_MAYOR.DEBE IS 'VALOR TOTAL DEL DEBE (VALORES POSITIVOS) EN LA TABLA LIBRO_DIARIO';
COMMENT ON COLUMN FINANZAS.LIBRO_MAYOR.HABER IS 'VALOR TOTAL DEL HABER (VALORES NEGATIVOS) EN LA TABLA LIBRO_DIARIO';
COMMENT ON COLUMN FINANZAS.LIBRO_MAYOR.FECHA IS 'FECHA DE GENERACIÓN DEL LIBRO MAYOR';
COMMENT ON COLUMN FINANZAS.LIBRO_MAYOR.ESTADO IS 'ACTIVO (1), INACTIVO (0)';

ALTER TABLE FINANZAS.LIBRO_MAYOR
    ADD CONSTRAINT FK_PLANCONTABLE_LIBROMAYOR FOREIGN KEY (PLAN_CONTABLE_COD)
        REFERENCES FINANZAS.PLAN_CONTABLE (CODIGO);

ALTER TABLE FINANZAS.LIBRO_MAYOR
    ADD CONSTRAINT FK_PERIODO_LIBROMAYOR FOREIGN KEY (PERIODO_COD)
        REFERENCES FINANZAS.PERIODO (CODIGO);

CREATE TABLE FINANZAS.CONCEPTO
(
    CODIGO               SERIAL                NOT NULL PRIMARY KEY,
    NOMBRE               CHARACTER VARYING(20) NOT NULL,
    DESCRPCION           CHARACTER VARYING(100),
    TIPO                 BOOLEAN               NOT NULL,
    ESTADO               BOOLEAN               NOT NULL,
    PLAN_CONTABLE_CODIGO INT                   NOT NULL
);

ALTER TABLE FINANZAS.CONCEPTO
    ADD CONSTRAINT FK_PLANCONTABLE_CONCEPTO_PL FOREIGN KEY (PLAN_CONTABLE_CODIGO)
        REFERENCES FINANZAS.PLAN_CONTABLE (CODIGO);

COMMENT ON TABLE FINANZAS.CONCEPTO
    IS 'TABLA DONDE SE ALMACENAN LOS DATOS DE CADA CARGO O LOS CONCEPTOS ';

COMMENT ON COLUMN FINANZAS.CONCEPTO.CODIGO
    IS 'LLAVE PRIMARIA DE LA TABLA CONCEPTO, CODIGO DEL CARGO';

COMMENT ON COLUMN FINANZAS.CONCEPTO.DESCRPCION
    IS 'FUNCIONES DEL CARGO ';

COMMENT ON COLUMN FINANZAS.CONCEPTO.TIPO
    IS 'DEFINE EL TIPO DEL CARGO Y LOS VALORES SON: (1)DEBE (0)HABER';

COMMENT ON COLUMN FINANZAS.CONCEPTO.ESTADO
    IS 'ESTE ATRIBUTO DEFINE EL ESTADO DE ACTIVIDAD O INACTIVIDAD DEL CARGO DONDE: (1) ACTIVO (0) INACTIVO';

COMMENT ON COLUMN FINANZAS.CONCEPTO.PLAN_CONTABLE_CODIGO
    IS 'CODIGO DE LA TABLA PLAN CONTABLE';

COMMENT ON COLUMN FINANZAS.CONCEPTO.NOMBRE
    IS 'NOMBRE DEL CARGO';

CREATE TABLE FINANZAS.LIBRO_DIARIO
(
    ASIENTO      SERIAL PRIMARY KEY NOT NULL,
    FECHA        DATE               NOT NULL,
    VALOR        DECIMAL            NOT NULL,
    PERIODO_COD  INT                NOT NULL,
    CONCEPTO_COD INT                NOT NULL,
    ESTADO       BOOLEAN            NOT NULL
);

COMMENT ON TABLE FINANZAS.LIBRO_DIARIO
    IS 'TABLA DONDE SE ALMACENAN EL LIBRO DIARIO ';

COMMENT ON COLUMN FINANZAS.LIBRO_DIARIO.ASIENTO IS 'CÓDIGO SECUENCIAL DEL MOVIMIENTO CONTABLE';
COMMENT ON COLUMN FINANZAS.LIBRO_DIARIO.FECHA IS 'FECHA DEL MOVIMIENTO CONTABLE';
COMMENT ON COLUMN FINANZAS.LIBRO_DIARIO.VALOR IS 'VALOR DEL ASIENTO CONTABLE';
COMMENT ON COLUMN FINANZAS.LIBRO_DIARIO.PERIODO_COD IS 'CÓDIGO DEL PERIODO CONTABLE';
COMMENT ON COLUMN FINANZAS.LIBRO_DIARIO.CONCEPTO_COD IS 'CÓDIGO DEL CONCEPTO CONTABLE';
COMMENT ON COLUMN FINANZAS.LIBRO_DIARIO.ESTADO IS 'ACTIVO (1), INACTIVO(0)';

ALTER TABLE FINANZAS.LIBRO_DIARIO
    ADD CONSTRAINT FK_LIBRODIARIO_PERIODO FOREIGN KEY (PERIODO_COD)
        REFERENCES FINANZAS.PERIODO (CODIGO);

ALTER TABLE FINANZAS.LIBRO_DIARIO
    ADD CONSTRAINT FK_LIBRODIARIO_CONCEPTO FOREIGN KEY (CONCEPTO_COD)
        REFERENCES FINANZAS.CONCEPTO (CODIGO);

CREATE SCHEMA FACTURACION;

CREATE TABLE FACTURACION.CATEGORIA_PRODUCTO
(
    CODIGO         INT                    NOT NULL,
    NOMBRE         CHARACTER VARYING(50)  NOT NULL,
    CARACTERISTICA CHARACTER VARYING(200) NOT NULL,
    PRIMARY KEY (CODIGO)
);
COMMENT ON COLUMN FACTURACION.CATEGORIA_PRODUCTO.CARACTERISTICA IS 'CACTERISTICAS DE LA CATEGORÌA';
COMMENT ON COLUMN FACTURACION.CATEGORIA_PRODUCTO.NOMBRE IS 'NOMBRE CATEGORÌA';
COMMENT ON COLUMN FACTURACION.CATEGORIA_PRODUCTO.CODIGO IS 'CÛDIGO DE LA CATEGORÌA';

CREATE TABLE FACTURACION.CLIENTE
(
    CODIGO           INT                    NOT NULL,
    NOMBRE           CHARACTER VARYING(50)  NOT NULL,
    APELLIDO         CHARACTER VARYING(100) NOT NULL,
    TELEFONO         CHARACTER VARYING(10),
    CODIGO_POSTAL    CHARACTER VARYING(5),
    SEXO             CHARACTER(1)           NOT NULL,
    FECHA_NACIMIENTO DATE                   NOT NULL,
    POBLACION        CHARACTER VARYING(20)  NOT NULL,
    PRIMARY KEY (CODIGO)
);

COMMENT ON COLUMN FACTURACION.CLIENTE.NOMBRE IS 'NOMBRE CLIENTE';
COMMENT ON COLUMN FACTURACION.CLIENTE.APELLIDO IS 'APELLIDOS CLIENTE';
COMMENT ON COLUMN FACTURACION.CLIENTE.TELEFONO IS 'MOVIL';
COMMENT ON COLUMN FACTURACION.CLIENTE.POBLACION IS 'POBLACIÛN DONDE VIVE EL CLIENTE';

CREATE TABLE FACTURACION.PRODUCTO
(
    CODIGO           INT                    NOT NULL,
    NOMBRE           CHARACTER VARYING(50)  NOT NULL,
    CARACTERISTICA   CHARACTER VARYING(200) NOT NULL,
    CATE_PROD_CODIGO INT                    NOT NULL,
    PRIMARY KEY (CODIGO)
);

ALTER TABLE FACTURACION.PRODUCTO
    ADD CONSTRAINT FK_PRODUCTO_CATEG_PRODUCTO FOREIGN KEY
        (CATE_PROD_CODIGO)
        REFERENCES FACTURACION.CATEGORIA_PRODUCTO (CODIGO);

COMMENT ON COLUMN FACTURACION.PRODUCTO.CODIGO IS 'CODIGO DEL PRODUCTO';
COMMENT ON COLUMN FACTURACION.PRODUCTO.NOMBRE IS 'NOMBRE DEL PRODUCTO';
COMMENT ON COLUMN FACTURACION.PRODUCTO.CARACTERISTICA IS 'CARACTERISTICAS DE LA PRODUCTO';
COMMENT ON COLUMN FACTURACION.PRODUCTO.CATE_PROD_CODIGO IS 'CODIGO HEREDADO DE LA CATEGORIA DEL PRODUCTO';

CREATE TABLE FACTURACION.PROVEEDOR
(
    CODIGO     INT                    NOT NULL,
    NOMBRE     CHARACTER VARYING(100) NOT NULL,
    DIRECCION  CHARACTER VARYING(100) NOT NULL,
    TELEFONO   CHARACTER VARYING(12)  NOT NULL,
    PAGINA_WEB CHARACTER VARYING(100) NULL,
    PRIMARY KEY (CODIGO)
);

COMMENT ON COLUMN FACTURACION.PROVEEDOR.CODIGO IS 'N˙MERO RUT DADO POR LA DIAN';
COMMENT ON COLUMN FACTURACION.PROVEEDOR.NOMBRE IS 'NOMBRE PROVEEDOR';
COMMENT ON COLUMN FACTURACION.PROVEEDOR.DIRECCION IS 'DIRECCIÛN DEL PROVEEDOR';
COMMENT ON COLUMN FACTURACION.PROVEEDOR.TELEFONO IS 'MÛVIL';
COMMENT ON COLUMN FACTURACION.PROVEEDOR.PAGINA_WEB IS 'URL DE LA P·GINA WEB DEL PROVEEDOR';
COMMENT ON TABLE FACTURACION.PROVEEDOR IS 'TABLA DE PROVEEDORES';

CREATE TABLE FACTURACION.PROVEEDOR_PRODUCTO
(
    PRECIO_UNITARIO  INT            NOT NULL,
    FECHA_VIGENCIA   DATE           NOT NULL,
    PESO             NUMERIC(20, 4) NOT NULL,
    PROVEEDOR_CODIGO INT,
    PRODUCTO_CODIGO  INT,
    PRIMARY KEY (PROVEEDOR_CODIGO, PRODUCTO_CODIGO)
);

ALTER TABLE FACTURACION.PROVEEDOR_PRODUCTO
    ADD CONSTRAINT FK_PROVEEDOR_PRODUCTO_1 FOREIGN KEY (PROVEEDOR_CODIGO)
        REFERENCES FACTURACION.PROVEEDOR (CODIGO);

ALTER TABLE FACTURACION.PROVEEDOR_PRODUCTO
    ADD CONSTRAINT FK_PROVEEDOR_PRODUCTO_2 FOREIGN KEY (PRODUCTO_CODIGO)
        REFERENCES FACTURACION.PRODUCTO (CODIGO);

COMMENT ON TABLE FACTURACION.PROVEEDOR_PRODUCTO IS 'TABLA DE LOS PRODUCTOS QUE TENGO DE UN PROVEEDOR';
COMMENT ON COLUMN FACTURACION.PROVEEDOR_PRODUCTO.PRECIO_UNITARIO IS 'PRECIO UNITARIO DEL PRODUCTO';
COMMENT ON COLUMN FACTURACION.PROVEEDOR_PRODUCTO.FECHA_VIGENCIA IS 'FECHA DE VIGENCIA DEL PRODUCTO';
COMMENT ON COLUMN FACTURACION.PROVEEDOR_PRODUCTO.PESO IS 'PESO EN KILOGRAMOS DEL PRODUCTO';
COMMENT ON COLUMN FACTURACION.PROVEEDOR_PRODUCTO.PROVEEDOR_CODIGO IS 'CODIGO HEREDADO DEL PROVEEDOR';
COMMENT ON COLUMN FACTURACION.PROVEEDOR_PRODUCTO.PRODUCTO_CODIGO IS 'CODIGO HEREDADO DEL PRODUCTO';

CREATE TABLE FACTURACION.VENTA
(
    CODIGO         INT  NOT NULL,
    FECHA          DATE NOT NULL,
    CLIENTE_CODIGO INT,
    PRIMARY KEY (CODIGO)
);

ALTER TABLE FACTURACION.VENTA
    ADD CONSTRAINT FK_VENTA_1 FOREIGN KEY (CLIENTE_CODIGO)
        REFERENCES FACTURACION.CLIENTE (CODIGO);

COMMENT ON TABLE FACTURACION.VENTA IS
    'TABLA DE LAS VENTAS DETALLADO POR CLIENTE';
COMMENT ON COLUMN FACTURACION.VENTA.CODIGO IS
    'CODIGO DE LA FACTURA (NUMERO DADO POR LA DIAN)';
COMMENT ON COLUMN FACTURACION.VENTA.FECHA IS
    'FECHA DE VENTA DE LA FACTURA';
COMMENT ON COLUMN FACTURACION.VENTA.CLIENTE_CODIGO IS
    'CODIGO HEREDADO DEL CLIENTE';

CREATE TABLE FACTURACION.VENTA_DETALLE
(
    CANTIDAD         INT                      NOT NULL,
    DESCUENTO        NUMERIC(20, 4) DEFAULT 0 NOT NULL,
    VENTA_CODIGO     INT                      NOT NULL,
    PROVEEDOR_CODIGO INT,
    PRODUCTO_CODIGO  INT,
    PRIMARY KEY (VENTA_CODIGO, PROVEEDOR_CODIGO, PRODUCTO_CODIGO)
);

ALTER TABLE FACTURACION.VENTA_DETALLE
    ADD CONSTRAINT FK_VENTA_DETALLE_2 FOREIGN KEY
        (PROVEEDOR_CODIGO, PRODUCTO_CODIGO)
        REFERENCES FACTURACION.PROVEEDOR_PRODUCTO
            (PROVEEDOR_CODIGO, PRODUCTO_CODIGO);

ALTER TABLE FACTURACION.VENTA_DETALLE
    ADD CONSTRAINT FK_VENTA_DETALLE_1 FOREIGN KEY (VENTA_CODIGO)
        REFERENCES FACTURACION.VENTA (CODIGO);

COMMENT ON TABLE FACTURACION.VENTA_DETALLE IS 'TABLA DEL DETALLE DE LA VENTA';
COMMENT ON COLUMN FACTURACION.VENTA_DETALLE.CANTIDAD IS 'CANTIDAD DE PRODUCTO VENDIDO';
COMMENT ON COLUMN FACTURACION.VENTA_DETALLE.DESCUENTO IS 'DESCUENTO APLICADO AL PRODUCTO';
COMMENT ON COLUMN FACTURACION.VENTA_DETALLE.VENTA_CODIGO IS 'CODIGO HEREDADO DE LA VENTA';
COMMENT ON COLUMN FACTURACION.VENTA_DETALLE.PROVEEDOR_CODIGO IS 'CODIGO DEL PROVEEDOR HEREDADO DE PROVEEDOR_PRODUCTO';
COMMENT ON COLUMN FACTURACION.VENTA_DETALLE.PRODUCTO_CODIGO IS 'CODIGO DEL PRODUCTO HEREDADO DE PROVEEDOR_PRODUCTO';

CREATE SCHEMA NOMINA;

CREATE TABLE NOMINA.HOJA_VIDA
(

    DOCUMENTO        INT PRIMARY KEY,
    NOMBRE           VARCHAR(100) NOT NULL,
    APELLIDO         VARCHAR(100) NOT NULL,
    NACIMIENTO_FECHA DATE         NOT NULL,
    NACIMIENTO_LUGAR VARCHAR(100) NOT NULL,
    DIRECCION        VARCHAR(100) NOT NULL,
    TELEFONO         INT          NOT NULL

);

COMMENT ON COLUMN NOMINA.HOJA_VIDA.DOCUMENTO IS 'NÚMERO DE DOCUMENTO';
COMMENT ON COLUMN NOMINA.HOJA_VIDA.NOMBRE IS 'NOMBRE DE LA PERSONA';
COMMENT ON COLUMN NOMINA.HOJA_VIDA.APELLIDO IS 'APELLIDOS DE LA PERSONA';
COMMENT ON COLUMN NOMINA.HOJA_VIDA.NACIMIENTO_FECHA IS 'FECHA DE NACIMIENTO';
COMMENT ON COLUMN NOMINA.HOJA_VIDA.NACIMIENTO_LUGAR IS 'LUGAR DE NACIMIENTO';
COMMENT ON COLUMN NOMINA.HOJA_VIDA.DIRECCION IS 'DIRECCIÓN DE RESIDENCIA';
COMMENT ON COLUMN NOMINA.HOJA_VIDA.TELEFONO IS 'NÚMERO TELEFÓNICO';

CREATE TABLE NOMINA.DEPENDENCIA
(
    CODIGO            SERIAL PRIMARY KEY,
    NOMBRE            VARCHAR(100) NOT NULL,
    DEPENDENCIA_PADRE INT,
    ESTADO            BOOLEAN      NOT NULL,

    FOREIGN KEY (DEPENDENCIA_PADRE) REFERENCES NOMINA.DEPENDENCIA (CODIGO)
);

COMMENT ON COLUMN NOMINA.DEPENDENCIA.CODIGO IS 'CÓDIGO';
COMMENT ON COLUMN NOMINA.DEPENDENCIA.NOMBRE IS 'NOMBRE DE LA DEPENDENCIA';
COMMENT ON COLUMN NOMINA.DEPENDENCIA.DEPENDENCIA_PADRE IS 'CÓDIGO DEPENDENCIA PADRE';
COMMENT ON COLUMN NOMINA.DEPENDENCIA.ESTADO IS 'ACTIVO (1), INACTIVO (0)';

CREATE TABLE NOMINA.CARGO
(
    CODIGO       SERIAL PRIMARY KEY,
    NOMBRE       VARCHAR(100) NOT NULL,
    FUNCION      VARCHAR(100) NOT NULL,
    COMPETENCIAS VARCHAR(100) NOT NULL

);

COMMENT ON COLUMN NOMINA.CARGO.CODIGO IS 'CÓDIGO DEL CARGO';
COMMENT ON COLUMN NOMINA.CARGO.NOMBRE IS 'NOMBRE DEL CARGO';
COMMENT ON COLUMN NOMINA.CARGO.FUNCION IS 'FUNCIONES DEL CARGO';
COMMENT ON COLUMN NOMINA.CARGO.COMPETENCIAS IS 'COMPETENCIAS';

CREATE TABLE NOMINA.CONTRATO
(
    CODIGO          SERIAL PRIMARY KEY,
    FECHA_INICIO    DATE NOT NULL,
    FECHA_FIN       DATE NOT NULL,
    SALARIO         INT  NOT NULL,
    HOJA_VIDA_DOC   INT  NOT NULL,
    DEPENDENCIA_COD INT  NOT NULL,
    CARGO_COD       INT  NOT NULL,
    FOREIGN KEY (HOJA_VIDA_DOC) REFERENCES NOMINA.HOJA_VIDA (DOCUMENTO),
    FOREIGN KEY (DEPENDENCIA_COD) REFERENCES NOMINA.DEPENDENCIA (CODIGO),
    FOREIGN KEY (CARGO_COD) REFERENCES NOMINA.CARGO (CODIGO)


);

COMMENT ON COLUMN NOMINA.CONTRATO.CODIGO IS 'CÓDIGO DEL CONTRATO';
COMMENT ON COLUMN NOMINA.CONTRATO.FECHA_INICIO IS 'FECHA INICIO';
COMMENT ON COLUMN NOMINA.CONTRATO.FECHA_FIN IS 'FECHA FIN';
COMMENT ON COLUMN NOMINA.CONTRATO.SALARIO IS 'SALARIO';
COMMENT ON COLUMN NOMINA.CONTRATO.HOJA_VIDA_DOC IS 'DOCUMENTO DE LA HOJA DE VIDA';
COMMENT ON COLUMN NOMINA.CONTRATO.DEPENDENCIA_COD IS 'CÓDIGO DE LA DEPENDENCIA';
COMMENT ON COLUMN NOMINA.CONTRATO.CARGO_COD IS 'CÓDIGO DEL CARGO';

CREATE TABLE NOMINA.CONCEPTO
(
    CODIGO      SERIAL PRIMARY KEY,
    NOMBRE      VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(100) NOT NULL,
    TIPO        BOOLEAN      NOT NULL,
    FORMULA     VARCHAR(100) NOT NULL,
    ESTADO      BOOLEAN      NOT NULL

);

COMMENT ON COLUMN NOMINA.CONCEPTO.CODIGO IS 'CÓDIGO DEL CONCEPTO';
COMMENT ON COLUMN NOMINA.CONCEPTO.NOMBRE IS 'NOMBRE DEL CONCEPTO';
COMMENT ON COLUMN NOMINA.CONCEPTO.DESCRIPCION IS 'DESCRIPCION CONCEPTO';
COMMENT ON COLUMN NOMINA.CONCEPTO.TIPO IS 'DEVENGADO(1), DEDUCIDO (0)';
COMMENT ON COLUMN NOMINA.CONCEPTO.FORMULA IS 'FORMULA DE CALCULO';
COMMENT ON COLUMN NOMINA.CONCEPTO.ESTADO IS 'ACTIVO (1), INACTIVO (0)';

CREATE TABLE NOMINA.PERIODO
(
    CODIGO       SERIAL PRIMARY KEY,
    FECHA_INICIO DATE    NOT NULL,
    FECHA_FIN    DATE    NOT NULL,
    ESTADO       BOOLEAN NOT NULL
);

COMMENT ON COLUMN NOMINA.PERIODO.CODIGO IS 'CÓDIGO DEL PERIODO';
COMMENT ON COLUMN NOMINA.PERIODO.FECHA_FIN IS 'FECHA FINAL';
COMMENT ON COLUMN NOMINA.PERIODO.FECHA_INICIO IS 'FECHA DE INICIO';
COMMENT ON COLUMN NOMINA.PERIODO.ESTADO IS 'ACTIVO (1), INACTIVO (0)';

CREATE TABLE NOMINA.NOMINA
(
    CONTRATO_COD   INT          NOT NULL,
    CONCEPTO_COD   INT          NOT NULL,
    PERIODO_COD    INT          NOT NULL,
    VALOR          INT          NOT NULL,
    USUARIO_INSERT VARCHAR(100) NOT NULL,
    FECHA_INSERT   DATE         NOT NULL,
    USUARIO_UPDATE VARCHAR(100) NOT NULL,
    FECHA_UPDATE   VARCHAR(100) NOT NULL,
    FOREIGN KEY (CONCEPTO_COD) REFERENCES NOMINA.CONCEPTO (CODIGO),
    FOREIGN KEY (CONTRATO_COD) REFERENCES NOMINA.CONTRATO (CODIGO),
    FOREIGN KEY (PERIODO_COD) REFERENCES NOMINA.PERIODO (CODIGO),
    PRIMARY KEY (CONTRATO_COD, CONCEPTO_COD, PERIODO_COD)

);

COMMENT ON COLUMN NOMINA.NOMINA.CONCEPTO_COD IS 'CÓDIGO DEL CONCEPTO';
COMMENT ON COLUMN NOMINA.NOMINA.CONTRATO_COD IS 'CÓDIGO DEL CONTRATO';
COMMENT ON COLUMN NOMINA.NOMINA.PERIODO_COD IS 'CÓDIGO DEL PERIODO';
COMMENT ON COLUMN NOMINA.NOMINA.VALOR IS 'VALOR LIQUIDADO';
COMMENT ON COLUMN NOMINA.NOMINA.USUARIO_INSERT IS 'USUARIO QUE HIZO INSERT';
COMMENT ON COLUMN NOMINA.NOMINA.FECHA_INSERT IS 'FECHA QUE SE HIZO INSERT';
COMMENT ON COLUMN NOMINA.NOMINA.USUARIO_UPDATE IS 'USUARIO QUE HIZO UPDATE';
COMMENT ON COLUMN NOMINA.NOMINA.FECHA_UPDATE IS 'FECHA QUE SE HIZO UPDATE';

CREATE SCHEMA SEGURIDAD;

CREATE TABLE SEGURIDAD.USUARIO
(
    CODIGO       SERIAL                              NOT NULL,
    NOMBRE       CHARACTER VARYING(40)               NOT NULL,
    EMAIL        CHARACTER VARYING(30)               NOT NULL,
    PASSWORD     CHARACTER VARYING(75)               NOT NULL,
    FECHA_INICIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FECHA_FIN    TIMESTAMP,
    TIPO         INTEGER                             NOT NULL,
    PRIMARY KEY (CODIGO)
);
COMMENT ON TABLE SEGURIDAD.USUARIO IS 'PERSONAS REGISTRADAS EN EL SISTEMA';

COMMENT ON COLUMN SEGURIDAD.USUARIO.CODIGO IS 'CÓDIGO DEL USUARIO';
COMMENT ON COLUMN SEGURIDAD.USUARIO.NOMBRE IS 'NOMBRE DEL USUARIO';
COMMENT ON COLUMN SEGURIDAD.USUARIO.EMAIL IS 'EMAIL DEL USUARIO ';
COMMENT ON COLUMN SEGURIDAD.USUARIO.PASSWORD IS 'CONTRASEÑA ENCRIPTADA DEL USUARIO';
COMMENT ON COLUMN SEGURIDAD.USUARIO.FECHA_INICIO IS 'FECHA INICIO ACCESO AL SISTEMA';
COMMENT ON COLUMN SEGURIDAD.USUARIO.FECHA_FIN IS 'FECHA FINAL ACCESO AL SISTEMA';
COMMENT ON COLUMN SEGURIDAD.USUARIO.TIPO IS 'INTERNO(1), LDAP(2)';

CREATE TABLE SEGURIDAD.ROL
(
    CODIGO      SERIAL                 NOT NULL,
    NOMBRE      CHARACTER VARYING(30)  NOT NULL,
    DESCRIPCION CHARACTER VARYING(250),
    ESTADO      BOOLEAN DEFAULT 'TRUE' NOT NULL,
    PRIMARY KEY (CODIGO)
);
COMMENT ON TABLE SEGURIDAD.ROL IS 'ROLES DE ACCESO AL SISTEMA';

COMMENT ON COLUMN SEGURIDAD.ROL.CODIGO IS 'CÓDIGO DEL ROL';
COMMENT ON COLUMN SEGURIDAD.ROL.NOMBRE IS 'NOMBRE DEL ROL';
COMMENT ON COLUMN SEGURIDAD.ROL.DESCRIPCION IS 'DESCRIPCIÓN DEL ROL';
COMMENT ON COLUMN SEGURIDAD.ROL.ESTADO IS 'ACTIVO(1), INACTIVO(0)';

CREATE TABLE SEGURIDAD.PERMISO
(
    CODIGO      SERIAL                 NOT NULL,
    NOMBRE      CHARACTER VARYING(30)  NOT NULL,
    DESCRIPCION CHARACTER VARYING(250) NOT NULL,
    ESTADO      BOOLEAN DEFAULT 'TRUE' NOT NULL,
    PRIMARY KEY (CODIGO)
);
COMMENT ON TABLE SEGURIDAD.PERMISO IS 'PERMISOS DE ACCESO A MÓDULOS';

COMMENT ON COLUMN SEGURIDAD.PERMISO.CODIGO IS 'CÓDIGO DEL PERMISO';
COMMENT ON COLUMN SEGURIDAD.PERMISO.NOMBRE IS 'NOMBRE DEL PERMISO';
COMMENT ON COLUMN SEGURIDAD.PERMISO.DESCRIPCION IS 'DESCRIPCIÓN DEL PERMISO';
COMMENT ON COLUMN SEGURIDAD.PERMISO.ESTADO IS 'ACTIVO(1), INACTIVO(0)';

CREATE TABLE SEGURIDAD.USUARIO_LOG
(
    CODIGO      SERIAL                              NOT NULL,
    FECHA       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    USUARIO_COD INTEGER                             NOT NULL,
    PROCESO     CHARACTER VARYING(50)               NOT NULL,
    DML         CHARACTER VARYING(50)               NOT NULL,
    PRIMARY KEY (CODIGO)
);
COMMENT ON TABLE SEGURIDAD.USUARIO_LOG IS 'HISTORIAL DE ACCIONES DE UN USUARIO';

COMMENT ON COLUMN SEGURIDAD.USUARIO_LOG.CODIGO IS 'CÓDIGO SECUENCIAL DEL LOG';
COMMENT ON COLUMN SEGURIDAD.USUARIO_LOG.FECHA IS 'FECHA DE LOG';
COMMENT ON COLUMN SEGURIDAD.USUARIO_LOG.USUARIO_COD IS 'CODIGO DEL USUARIO';
COMMENT ON COLUMN SEGURIDAD.USUARIO_LOG.PROCESO IS 'NOMBRE DEL PROCESO QUE EJECUTO EL LOG';
COMMENT ON COLUMN SEGURIDAD.USUARIO_LOG.DML IS 'OPERACIÓN DML QUE REALIZO EL USUARIO';

ALTER TABLE SEGURIDAD.USUARIO_LOG
    ADD CONSTRAINT FK_USUARIO_USUARIO_LOG FOREIGN KEY (USUARIO_COD) REFERENCES SEGURIDAD.USUARIO (CODIGO);

CREATE TABLE SEGURIDAD.ROL_USUARIO
(
    USUARIO_COD INTEGER                             NOT NULL,
    ROL_COD     INTEGER                             NOT NULL,
    FECHA       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (USUARIO_COD, ROL_COD)
);
COMMENT ON TABLE SEGURIDAD.ROL_USUARIO IS 'ASOCIACIÓN DE UN ROL CON UN USUARIO';

COMMENT ON COLUMN SEGURIDAD.ROL_USUARIO.USUARIO_COD IS 'CÓDIGO DE USUARIO';
COMMENT ON COLUMN SEGURIDAD.ROL_USUARIO.ROL_COD IS 'CÓDIGO DEL ROL';
COMMENT ON COLUMN SEGURIDAD.ROL_USUARIO.FECHA IS 'FECHA DE ASIGNADO DEL ROL AL USUARIO';

ALTER TABLE SEGURIDAD.ROL_USUARIO
    ADD CONSTRAINT FK_USUARIO_ROL_USUARIO FOREIGN KEY (USUARIO_COD) REFERENCES SEGURIDAD.USUARIO (CODIGO);
ALTER TABLE SEGURIDAD.ROL_USUARIO
    ADD CONSTRAINT FK_ROL_ROL_USUARIO FOREIGN KEY (ROL_COD) REFERENCES SEGURIDAD.ROL (CODIGO);

CREATE TABLE SEGURIDAD.ROL_PERMISO
(
    PERMISO_COD INTEGER                             NOT NULL,
    ROL_COD     INTEGER                             NOT NULL,
    FECHA       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (PERMISO_COD, ROL_COD)
);
COMMENT ON TABLE SEGURIDAD.ROL_PERMISO IS 'ASOCIACIÓN DE UN ROL CON UN PERMISO';

COMMENT ON COLUMN SEGURIDAD.ROL_PERMISO.PERMISO_COD IS 'CÓDIGO DEL PERMISO';
COMMENT ON COLUMN SEGURIDAD.ROL_PERMISO.ROL_COD IS 'CÓDIGO DEL ROL';
COMMENT ON COLUMN SEGURIDAD.ROL_PERMISO.FECHA IS 'FECHA DE ASIGNACIÓN DEL ROL AL USUARIO';

ALTER TABLE SEGURIDAD.ROL_PERMISO
    ADD CONSTRAINT FK_PERMISO_ROL_PERMISO FOREIGN KEY (PERMISO_COD) REFERENCES SEGURIDAD.PERMISO (CODIGO);
ALTER TABLE SEGURIDAD.ROL_PERMISO
    ADD CONSTRAINT FK_ROL_ROL_PERMISO FOREIGN KEY (ROL_COD) REFERENCES SEGURIDAD.ROL (CODIGO);
